name: Fetch Dependencies

on:
  schedule:
    - cron: '0 0 * * *' # Run daily

jobs:
  update-dependencies:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch Dependencies
      run: ./scripts/fetch_dependencies.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "update dependencies"
        commit-message: "update dependencies"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        base: indev
