name: macOS

on:
  pull_request:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        arch: [x86_64]
        mode: [release]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Get current date as package key
      id: cache_key
      run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

    - name: Checkout repository
      uses: actions/checkout@v4

    # Install system dependencies
    - name: Setup SDL2 frameworks
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: latest

    # Build the lib
    - name: Build MacroLibX
      run: make -j && make fclean && make debug 

    # Build the example
    - name: Build Example
      run: cd example && bash ./build.sh

